name: Handle release

on:
  release:
    types: [created, edited]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.20
      id: go

    - name: Check out code into GOPATH
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        path: go/src/github.com/monzo/envoy-preflight
        
    - name: Create bin
      run: mkdir -p ${{ github.workspace }}/go/bin

    - name: Get dependencies
      working-directory: go/src/github.com/monzo/envoy-preflight
      env:
        GOPATH: ${{ github.workspace	}}/go
      run: |
        go get -v -t -d ./...

    - name: Build
      working-directory: go/src/github.com/monzo/envoy-preflight
      env:
        GOPATH: ${{ github.workspace }}/go
      run: go build -v .
    
    - name: Archive binary
      uses: actions/upload-artifact@v3
      with:
        name: envoy-preflight
        path: ${{ github.workspace }}/go/src/github.com/monzo/envoy-preflight/envoy-preflight
        retention-days: 1

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build 
    permissions:
      contents: write
    steps:
    - name: Fetch binary
      uses: actions/download-artifact@v3
      with:
        name: envoy-preflight

    - name: Release binary
      uses: skx/github-action-publish-binaries@release-0.14
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'envoy-preflight'
